### ISSUE TITLE
Add support for insecure TLS

### ISSUE THREAD

**Issue by cpaggen** [allenrobel/netbox-tools#1]
Add _nb.http_session.verify = False_ to all code that uses pynetbox.api. Probably easier with a generic connection module that applies to all code samples?

**Comment by allenrobel** [comment]
Thanks Chris.  Will look into this.  In lib/netbox_config.py, we can read a new flag (e.g. ssl_verification) in lib/config.yml and toggle ssl verification on/off based on whatever the user has set there.

**Comment by allenrobel** [comment]
Modified lib.common to add support for ignoring certs and cert warnings.
Updated lib/config/config.yml with two additional config options for the above.
Common hash: ec132334c297146efbf9b8f0ba8ce7d85d6fadb2
